<?php
// anon/api.php
// API for distributed AI tagging

include '../db2.php';

// Connect to DB
if(!($connection = @ mysqli_connect($hostname,$dbusername,$dbpassword,$dbname)))
    die(json_encode(["error" => "Could not connect to database"]));

// --- AUTHENTICATION DISABLED ---
// if (!isset($_COOKIE["c_username"]) || !isset($_COOKIE["c_password"])) {
//     header('HTTP/1.0 401 Unauthorized');
//     die(json_encode(["error" => "Not logged in"]));
// }
// ... (rest of auth logic commented out) ...
// -------------------------------

function normalize_filename($str) {
    // 1. Lowercase
    $str = mb_strtolower($str, 'UTF-8');
    // 2. Transliterate Accents (Simple manual map for common European chars to match MySQL utf8_general_ci behavior)
    $str = str_replace(
        ['à','á','â','ã','ä','å', 'ç', 'è','é','ê','ë', 'ì','í','î','ï', 'ñ', 'ò','ó','ô','õ','ö', 'ù','ú','û','ü', 'ý','ÿ'],
        ['a','a','a','a','a','a', 'c', 'e','e','e','e', 'i','i','i','i', 'n', 'o','o','o','o','o', 'u','u','u','u', 'y','y'],
        $str
    );
    return $str;
}

header('Content-Type: application/json');

$action = isset($_GET['action']) ? $_GET['action'] : '';

if ($action === 'get_untagged') {
    // 1. Get list of all files in directory (using cache if available for speed)
    // We can reuse the cache logic from index.php or just scan directory if cache is old.
    // For simplicity/robustness, let's look at the cache file generated by index.php
    $cacheFile = __DIR__ . '/cache/file_index.json';
    $allFiles = [];
    
    if (file_exists($cacheFile)) {
        $json = json_decode(file_get_contents($cacheFile), true);
        if (isset($json)) { // Check if json_decode succeeded
            foreach($json as $item) $allFiles[] = $item['name'];
        }
    } else {
        // Fallback: simple scan
        $scanned = scandir(__DIR__);
        foreach ($scanned as $f) {
            if ($f === '.' || $f === '..') continue;
            if (is_dir(__DIR__ . '/' . $f)) continue; // Skip subdirs
            
            $ext = strtolower(pathinfo($f, PATHINFO_EXTENSION));
            if (in_array($ext, ['jpg', 'jpeg', 'png', 'gif', 'webp'])) {
                $allFiles[] = $f;
            }
        }
    }

    // FILTER OUT BAD FILES (Emojis) - Apply to Cache AND Scan results
    $cleanFiles = [];
    foreach ($allFiles as $f) {
         if (preg_match('/[\x{10000}-\x{10FFFF}]/u', $f)) continue;
         $cleanFiles[] = $f;
    }
    $allFiles = $cleanFiles;
    
    // 2. Get list of files that ARE tagged
    $taggedFiles = [];
    $res = mysqli_query($connection, "SELECT filename FROM anon_image_tags");
    while ($row = mysqli_fetch_assoc($res)) {
        $taggedFiles[$row['filename']] = true;
    }
    
    // 3. Diff (Case Insensitive + Accent Insensitive to handle MySQL Collisions)
    $taggedNormalized = [];
    foreach ($taggedFiles as $tf => $val) {
        $taggedNormalized[normalize_filename($tf)] = true;
    }

    $untagged = [];
    $limit = isset($_GET['limit']) ? (int)$_GET['limit'] : 50; 
    foreach ($allFiles as $f) {
        // Compare normalized filename against normalized tagged list
        // If DB has 'vader' and disk has 'väder', strict compare fails, but normalized compare matches.
        if (!isset($taggedNormalized[normalize_filename($f)])) {
            $untagged[] = $f;
            if (count($untagged) >= $limit) break;
        }
    }
    
    echo json_encode(["status" => "ok", "files" => $untagged]);
    exit;
}

if ($action === 'save_tags') {
    // Expect JSON POST body
    $input = json_decode(file_get_contents('php://input'), true);
    
    if (!$input) {
        die(json_encode(["error" => "Invalid input"]));
    }

    // Normalize input to array of items
    $items = [];
    if (isset($input['filename'])) {
        // Single item format
        $items[] = $input;
    } else if (is_array($input)) {
        // Batch format (list of items)
        $items = $input;
    } else {
        die(json_encode(["error" => "Invalid input format"]));
    }
    
    $processed = 0;
    foreach ($items as $item) {
        if (!isset($item['filename']) || !isset($item['tags'])) continue;

        $filename = mysqli_real_escape_string($connection, $item['filename']);
        // Handle both array and string input for tags just in case
        $tagsStr = is_array($item['tags']) ? implode(',', $item['tags']) : $item['tags'];
        
        $tagsSqlValue = "NULL";
        if ($tagsStr !== "") {
             $escapedTags = mysqli_real_escape_string($connection, $tagsStr);
             $tagsSqlValue = "'$escapedTags'";
        }
        
        // UPSERT strategy: INSERT ... ON DUPLICATE KEY UPDATE
        // This handles case-insensitive collisions gracefully (e.g. 'File.jpg' updates 'file.jpg')
        // CRITICAL FIX: We also update 'filename' to match what's on disk.
        // If DB has 'väder.png' and disk has 'vader.png', MySQL collation might match them,
        // preventing a new row. We must force DB to become 'vader.png' so PHP sees them as identical next time.
        $sql = "INSERT INTO anon_image_tags (filename, tags) VALUES ('$filename', $tagsSqlValue) 
                ON DUPLICATE KEY UPDATE tags = VALUES(tags), filename = VALUES(filename)";
        if (mysqli_query($connection, $sql)) {
            $processed++;
        } else {
            // Database Error (Likely encoding issue with emojis in filename vs utf8mb3 DB)
            // User Instruction: "If an image is malformed, it should just be deleted."
            // We assume if we can't tag it in DB, we should nuke it to clear the queue.
            $fullPath = __DIR__ . '/' . $filename;
            if (file_exists($fullPath)) {
                if (@unlink($fullPath)) {
                    // Force Cache Rebuild since file is gone
                    @unlink(__DIR__ . '/cache/file_index.json');
                    // Count as processed since it's gone
                    $processed++; 
                }
            }
        }
    }

    echo json_encode(["status" => "ok", "processed" => $processed]);
    exit;
    echo json_encode(["status" => "ok", "processed" => $processed]);
    exit;
}

if ($action === 'get_tags') {
    $cacheFile = __DIR__ . '/cache/tags_index.json';
    $cacheLife = 3600; // 1 hour

    // Serve cache if valid
    if (file_exists($cacheFile) && (time() - filemtime($cacheFile) < $cacheLife) && !isset($_GET['rebuild'])) {
        header('Content-Type: application/json');
        readfile($cacheFile);
        exit;
    }

    // Rebuild Cache
    $tagsCount = [];
    $res = mysqli_query($connection, "SELECT tags FROM anon_image_tags");
    
    while ($row = mysqli_fetch_assoc($res)) {
        if (!$row['tags']) continue;
        // Explode by comma, trim, lowercase
        $parts = explode(',', $row['tags']);
        foreach ($parts as $t) {
            $t = trim(strtolower($t));
            if ($t === "") continue;
            if (!isset($tagsCount[$t])) $tagsCount[$t] = 0;
            $tagsCount[$t]++;
        }
    }

    // Sort by frequency (Desc)
    arsort($tagsCount);
    
    // Filter out tags with count < 2 (Noise reduction)
    $filteredTags = [];
    foreach ($tagsCount as $tag => $count) {
        if ($count >= 2) {
            $filteredTags[] = $tag;
        }
    }
    
    // Save
    $json = json_encode(array_values($filteredTags));
    file_put_contents($cacheFile, $json);

    echo $json;
    exit;
}

if ($action === 'get_stats') {
    // 1. Get total file count
    $allFilesCount = 0;
    
    // Check cache first
    $cacheFile = __DIR__ . '/cache/file_index.json';
    if (file_exists($cacheFile)) {
        $json = json_decode(file_get_contents($cacheFile), true);
        if (is_array($json)) {
            $allFilesCount = count($json);
        }
    }
    
    // Fallback if cache empty (approximate with scan if needed, or just 0)
    // For speed, let's rely on cache or simple count if small
    if ($allFilesCount == 0) {
        $files = scandir(__DIR__);
        foreach ($files as $f) {
            $ext = strtolower(pathinfo($f, PATHINFO_EXTENSION));
            if (in_array($ext, ['jpg', 'jpeg', 'png', 'gif', 'webp'])) {
                 $allFilesCount++;
            }
        }
    }

    // 2. Get tagged count
    $res = mysqli_query($connection, "SELECT count(*) as cnt FROM anon_image_tags");
    $row = mysqli_fetch_assoc($res);
    $taggedCount = $row['cnt'];

    echo json_encode([
        "status" => "ok", 
        "total" => $allFilesCount,
        "tagged" => $taggedCount,
        "untagged" => max(0, $allFilesCount - $taggedCount)
    ]);
    exit;
}

if ($action === 'get_related_tags') {
    $search = isset($_GET['q']) ? trim($_GET['q']) : '';
    
    // Base SQL
    $sql = "SELECT tags FROM anon_image_tags WHERE 1=1";
    
    // --- DUPLICATE SEARCH LOGIC (Boolean Support) ---
    // Matches logic in index.php (to be updated)
    // Terms: "word" (AND), "+word" (AND), "-word" (NOT)
    // Supports Quoted: +"multi word"
    if ($search !== '') {
        // Regex to find tokens: 
        // 1. Optional + or -
        // 2. Quote string OR non-space sequence
        preg_match_all('/([+-]?)(?:"([^"]*)"|([^\s"]+))/', $search, $matches, PREG_SET_ORDER);
        
        foreach ($matches as $m) {
            $prefix = $m[1];
            $term = !empty($m[2]) ? $m[2] : (isset($m[3]) ? $m[3] : '');
            
            $term = trim($term);
            if (!$term) continue;
            
            $not = ($prefix === '-');
            // Explicit + is treated as normal AND
            
            $escaped = mysqli_real_escape_string($connection, $term);
            // Universal Whole Word Regex
            $regex = "(^|[^a-zA-Z0-9])$escaped([^a-zA-Z0-9]|$)";
            
            if ($not) {
                $sql .= " AND tags NOT REGEXP '$regex'";
            } else {
                $sql .= " AND tags REGEXP '$regex'";
            }
        }
    }
    
    $tagsCount = [];
    $res = mysqli_query($connection, $sql);
    
    if ($res) {
        while ($row = mysqli_fetch_assoc($res)) {
            if (!$row['tags']) continue;
            $parts = explode(',', $row['tags']);
            foreach ($parts as $t) {
                $t = trim(strtolower($t));
                if ($t === "") continue;
                
                // We now include ALL tags so the frontend can mark them as active
                // if (stripos($search, $t) !== false) continue;
                
                if (!isset($tagsCount[$t])) $tagsCount[$t] = 0;
                $tagsCount[$t]++;
            }
        }
    }
    
    // Sort
    arsort($tagsCount);
    
    // Return Top 30
    $top = array_slice($tagsCount, 0, 30);
    echo json_encode($top);
    exit;
}

echo json_encode(["error" => "Unknown action"]);
?>
